### ISSUE TITLE
Feature request: resolve parts in vscode

### ISSUE THREAD

**Issue by henrikrudstrom** [sanity-io/vscode-sanity#1]
It would be awesome to be able to follow the part imports that vscode currently does not understand ie: `import DefaultSelect from 'part:@sanity/components/selects/default';`

i understand there are some intricacies in that they dont always resolve to the same code depending on which plugins are installed and whether they can be resolved without firing up sanity?

Cherry on top would be a eslint plugin!

**Comment by runeb** [comment]
Parts were deprecated with v3 of Sanity
