### ISSUE TITLE
how make use of vscode-sanity

### ISSUE THREAD

**Issue by SADANANDKUMAR** [sanity-io/vscode-sanity#11]
#vscode-sanity  
I have added successfully sanity.io in vscode now how to make use of it while clicking on #execute query its shows an error like .....Could not resolve sanity.json configuration file

**Comment by davidadeola** [comment]
Hey @SADANANDKUMAR ,

The issue is because your windows PC has Powershell blocking its access from creating an internal access to VSCode using powershell.

A quick solution is to use: 

npx sanity init

This will enable it access it Globally.

**Comment by SADANANDKUMAR** [comment]
@davidadeola  thanks its working now
