### ISSUE TITLE
Get projectId and dataset from `.env` instead

### ISSUE THREAD

**Issue by Svish** [sanity-io/vscode-sanity#17]
Using the new v3 setup, with for example the studio embedded in a Next.js app, there is no `sanity.json` file anywhere, and the extension should instead use the environment variables defined in `.env`.

Probably these two:
```
SANITY_API_PROJECT_ID
SANITY_API_DATASET
```

**Comment by runeb** [comment]
Apologies for the delay on this. The plugin only supported v2 of Sanity which had a different configuration format. We have now updated the plugin to support the newer sanity.cli.js|ts config file.
